import "./globals.css";
import { Rubik } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "./components/BootstrapClient";
import Navbar from "./components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
    title: "Karaoke-V2",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={rubik.className}
                style={{ backgroundColor: "#333" }}
            >
                <Navbar></Navbar>
                {children}
                <BootstrapClient />
            </body>
        </html>
    );
}
